---
title: "Efficacy of a Novel Antihypertensive Drug in treating Stage 1 Hypertension "
author: "Harchit Kaur" 
date: today 
project: 
  output-dir: Output
  execute-dir: project
toc: true 
abstract-title: "Research question:"
abstract: "Does the new drug (AH-27) leads to a greater reduction in SBP?"
format: 
  html: 
    embed-resources: true
    number-sections: true
    code-fold: true
editor: visual 
editor_options: 
  chunk_output_type: console
execute:
  warning: false 
  message: false
  freeze: false
---

## Prepare Session

Load the required libraries, import, screen and correct the data.

```{r}
#| label: prepare session 
#| echo: false 
#| output: false 

  library(pastecs)
  library(ggplot2)
  library(ggpubr); theme_set(theme_bw())
  library(GGally)
  library(performance)
  library(MuMIn)
  library(ggeffects)
  library(tidyverse)
  library(broom)
  library(car)

  library(knitr)                                     # To render tables

# Import data
  BP <- read.csv("data/processed/hyper-tension.csv", stringsAsFactors= T) 

  
str(BP) # shows data typ and preview of the columns
summary(BP) #numeric → mean, min, max, etc.+ factors → counts per category
```

## Explore the data

```{r}

```

### Nummerically

```{r}
#| echo: false
2 * 2
```

### Graphically

```{r}

```

## Fit model

### Formulate and compare

```{r}

```

### Validate the preferred model

```{r}

```

## Interpret model

```{r}

```
